name: Sync images

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hhyasdf/image-sync-action@v1.1
        with:
          auth_file: ./auth.yaml
          images_file: ./images.yaml
          version: latest
          proc: 6
        env:
          ALIYUN_USERNAME: ${{ secrets.ALIYUN_USERNAME }}
          ALIYUN_PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}
          HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
